### ISSUE TITLE
module 'sharepy' has no attribute 'auth'

### ISSUE THREAD

**Issue by jcastanien** [JonathanHolvey/sharepy#53]
Hi, I'm a bit of a novice, but the documentation code from the read me (Requests authentication) triggers an error "module 'sharepy' has no attribute 'auth'".

print(dir(sharepy)) which printed ['SharePointSession', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'connect', 'load', 'session']. I was expecting to see auth listed. Where am I going wrong?

I read the release notes from Jan 2021, is it possible the read me documentation hasn't been updated? 

This package appears to be exactly what i'm looking for, I'm just having trouble getting it up and running. Thanks for any response in advance!

**Comment by dkinneyBU** [comment]
I am getting the same error. with sharepy 1.3.0

**Comment by KatherineWeller** [comment]
I am having this same issue, also on version 1.3.0.

**Comment by Boulder08** [comment]
Looks like the examples are not clear on what version they are meant for. The example will work with the pre-version of 2.0 but not on the latest official release.

Use pip install sharepy==2.0.0b1.post2 to install the latest (as of now) version.
